### PR TITLE
Interventions updates

### PR DESCRIPTION
**Pull request by nicolasreed**
This PR adds support for manipulating the entire interventions section.

- Support for adding/updating human and vectorPop interventions.
- Support for each specific intervention sub-type (GVI, MDA, VectorPop, etc.).

Note: Increased support for Vaccine interventions will be in a separate PR and version.

### CODE REVIEW

**Comment by nicolasreed** [comment]
@Baguage Would you like to look this over before one of us merges it into master?

Everything seems to be working fine, but it never hurts to have an extra pair of eyes for review.

Note: I will update the version and Changelog outside of this PR once it is merged (I want to test the new tagging stuff along with it).

Thanks. :smile:

**Comment by Baguage** [comment]
There may be a typo components function (Deploy class)

    @property
    def components(self):
        **component_ids** = []

        for component in self.et.findall("component"):
            **components_ids**.append(component.attrib["id"])

        return component_ids

However, I guess code is not used for now and can be updated in next version

**Comment by nicolasreed** [comment]
I'll fix that typo and do a rebase, thanks for catching it!

**Comment by nicolasreed** [comment]
Typo fixed.

**Pull request merged**
