### PR TITLE
Human interventions deployments update

### PR DESCRIPTION
**Pull request by nicolasreed**
~~Do not merge yet.~~

### CODE REVIEW

**Comment by nicolasreed** [comment]
One issue that has arisen during this update is that deployments have no set way of being uniquely identified from one another in Schema v32 (Note: This does not seem to have changed in 33/34, either).

I opened an [issue](https://github.com/SwissTPH/openmalaria/issues/116) on the SwissTPH/openmalaria repository to see if adding a unique identifier would be of any benefit.

**Comment by dhardy** [comment]
Is there a need for *anything* to refer to a `deployment` element? That was never a design factor.

**Comment by nicolasreed** [comment]
Thanks for your input, @dhardy.

My original intention was to have some sort of 'deploy' checkbox attached to each 'intervention' in the user interface for the VecNet site. After

**Comment by dhardy** [comment]
Glad you found a solution Nick.

**Pull request merged**
